# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0003_remove_stripeaccount_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe.StripeAccount'),
        ),
    ]
