# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 21:46
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(default=47408, max_length=10),
            preserve_default=False,
        ),
    ]
