# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import reuserat.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_type',
            field=models.CharField(choices=[('Check', 'Check'), ('Paypayl', 'Paypal')], default='Paypal', max_length=255, verbose_name='Payment Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[reuserat.users.models.phone_validator]),
        ),
    ]
