# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_stripe_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Bloomington', max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address_apartment',
            field=models.CharField(max_length=30, verbose_name='Apartment #'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(max_length=30, verbose_name='Address Line #'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_type',
            field=models.CharField(choices=[('Check', 'Check'), ('Direct Deposit', 'Direct Deposit'), ('Paypal', 'Paypal')], default='Check', max_length=255, verbose_name='Payment Type'),
        ),
    ]
