# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0006_remove_paypalaccount_user'),
        ('users', '0002_auto_20170302_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='paypal_email',
        ),
        migrations.AddField(
            model_name='user',
            name='paypal_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe.PaypalAccount'),
        ),
    ]
