# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import reuserat.address.models
import reuserat.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('users', '0003_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=reuserat.address.models.AddressField(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[reuserat.users.models.phone_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Check', 'Check'), ('Paypayl', 'Paypal')], max_length=255, verbose_name='Payment Type'),
        ),
    ]
