# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170304_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ssn_last_four',
            field=models.IntegerField(null=True, verbose_name='Last 4 Digits of SSN'),
        ),
    ]
