# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 01:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import reuserat.address.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170201_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=reuserat.address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='address.Address'),
        ),
    ]
