# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 13:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_ssn_last_four'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ssn_last_four',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^[\\d]{4}$')], verbose_name='Last 4 Digits of SSN'),
        ),
    ]
