# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import reuserat.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170201_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Check', 'Check'), ('Paypal', 'Paypal')], max_length=255, null=True, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[reuserat.users.models.phone_validator]),
        ),
    ]
