# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170204_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_type',
            field=models.CharField(choices=[('Check', 'Check'), ('Paypal', 'Paypal')], max_length=255, null=True, verbose_name='Payment Type'),
        ),
    ]
