# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 01:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170719_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='ssn_last_four',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^[\\d]{4}$')], verbose_name='Last 4 Digits of SSN'),
        ),
    ]
