# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170719_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paypal_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe.PaypalAccount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe.StripeAccount'),
        ),
    ]
