# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170719_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ssn_last_four',
        ),
    ]
