# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170719_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Birth Date'),
        ),
    ]
