sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 2

before_install:
 - sudo apt-get -o Dpkg::Options::="--force-confnew" install --force-yes docker-engine=${DOCKER_VERSION}
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose -f dev.yml build
  - docker-compose -f dev.yml run django py.test

