sudo: required
services:
  - docker
before_install:
  - printenv > .env
  - cat .env
  - docker-compose -f test.yml build
  - docker ps -a

script: docker-compose -f test.yml run django py.test

python:
- '3.5'
deploy:
  provider: heroku
  api_key:
    secure: k/LTX3Hk8vd9WOpL+I8V1E4bfmMLU+x9oratIAjB/4DipmLbY34nZZzMX4o7tZR9I3WTqlNbX5oZwg35iYHY/S5sbopkj4ohUj8JumXm0QxqXHtkuH4rspyqYCo+jkpauz8d627QbQMmRRl9lSJB6clI0qKwvq4EjhioPLPbXa2VNYTCyswlnauzIPImev5tUYtbh1iJ+GOp2hc4bwBH2cxZCb+dCEqoeLAzWx5EJAqr8/KrXtl3duNqdyvQpP+jcAeA7OGdCfCHhoDkV8yxoHt+K5B5f7sr5P3FxAAppb5+eQk2aCsW3m165rS9PFaY7YQomWrRckao41itTnJOz2QTjL519z1kNCJ1oi6N5mlLc3tGZSsWFEnDmWy0KCwvPNKs8jJeSmiV8b8SgQ483/kQH4Bcn+30tdWVLbxGORiZw93mNg2bR3BMi9Y5ywhVOgpg2UYx4ILzyHSw332xOj0tVxbE2RP7bpH9i5w4L8IEyQrZjKKFJ1wMPD0Rkryx5lIqBwLuBLyWghD/2q7caTEroc07SKoXu+TJocplBpysuyepSjjVsazwfvk+/ZCHW48dDFqsH4k6ZCOe+VW3UVRIOKBEGkxCAvbKZ0h4iACjt6dDJRMd0J4NEwX3tvPcstiBh8v2tDKCWKjWbp3T0jRhZDa/gjT+xZSqMbznqiQ=
  app: reuseratseller
  on:
    repo: jamesaud/ReuseRat
