language: python
python:
  - 3.6
sudo: required
services:
  - docker #Travis CI automatically routes builds to run on Trusty when services: docker is configured.
  - postgresql
env:
  DOCKER_COMPOSE_VERSION: 2
before_install:
  - sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  - sudo pip install docker-compose
  - docker-compose version

install:
  - docker-compose -f dev.yml build -d
  - docker-compose -f dev.yml up -d
script: docker-compose -f dev.yml run django py.test
