sudo: required
services:
  - docker
env:
  COMPOSE_VERSION: 1.12.0
before_install:
 - sudo rm /usr/local/bin/docker-compose
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - touch .env
 - printenv > .env

script:
  - docker-compose -f dev.yml build
  - docker-compose -f dev.yml run django py.test
