version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=reuserat

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=reuserat
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "35729:35729"
    links:
      - postgres
      - mailhog



  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=reuserat
    volumes:
      - .:/app
    links:
      - postgres



  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

