# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='stripe AccountId')),
                ('secret_key', models.CharField(max_length=255, verbose_name='stripe Secret')),
                ('publishable_key', models.CharField(max_length=255, verbose_name='stripe Publishable')),
            ],
        ),
    ]
