# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255, null=True, verbose_name='stripe AccountId')),
                ('secret_key', models.CharField(max_length=255, null=True, verbose_name='stripe Secret')),
                ('publishable_key', models.CharField(max_length=255, null=True, verbose_name='stripe Publishable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
