# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='account_holder_name',
            field=models.CharField(default='james', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='account_number_last_four',
            field=models.IntegerField(default=4444),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='account_number_length',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='routing_number_last_four',
            field=models.IntegerField(default=2222),
            preserve_default=False,
        ),
    ]
