# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0002_auto_20170212_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeaccount',
            name='user',
        ),
    ]
