# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0003_remove_stripeaccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeaccount',
            name='id',
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='account_number_token',
            field=models.CharField(max_length=255, null=True, verbose_name='account_token'),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='account_id',
            field=models.CharField(default='111111111', max_length=255, primary_key=True, serialize=False, verbose_name='stripe AccountId'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='publishable_key',
            field=models.CharField(default='2222222222', max_length=255, verbose_name='stripe Publishable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='secret_key',
            field=models.CharField(default='33333333', max_length=255, verbose_name='stripe Secret'),
            preserve_default=False,
        ),
    ]
