# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0003_auto_20170302_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeaccount',
            name='account_number_last_four',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='nomatch', message='Has to be 4 integers', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='routing_number_last_four',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='nomatch', message='Has to be 4 integers', regex='^\\d{4}$')]),
        ),
    ]
