# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0004_auto_20170216_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeaccount',
            name='account_number_token',
        ),
    ]
