# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0009_auto_20170315_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Funds Added', 'Funds Added'), ('Cash Out', 'Cash Out'), ('Credit', 'Credit'), ('Fee', 'Fee')], default='Funds Added', max_length=255, verbose_name='Transaction Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='message',
            field=models.CharField(default='test message', max_length=500),
            preserve_default=False,
        ),
    ]
