# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0012_transaction_check_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='check_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
