FROM python:3.5

ENV PYTHONUNBUFFERED 1

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt

COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./compose/django/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /start-dev.sh
RUN chmod +x /start-dev.sh

WORKDIR /app

# Install wkhtml which is necessary for pdf conversion.
RUN wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz \
        && tar -xf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz \
        && cp -r wkhtmltox/* /usr/

# Install npm & node and symlink the directory
RUN apt-get update \
    && apt-get install -y nodejs \
    && apt-get install -y npm \
    && ln -s /usr/bin/nodejs /usr/bin/node

RUN npm install -g bower

RUN apt-get install ruby-full -y

RUN apt-get install rubygems -y

RUN gem install bourbon

RUN pip install lob

ENTRYPOINT ["/entrypoint.sh"]

