# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0003_auto_20170206_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('handle', models.CharField(max_length=200)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.Shipment')),
            ],
        ),
    ]
