# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shopify_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
