# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='Not Sold', max_length=100),
        ),
    ]
