# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_auto_20170228_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'d': 'd'}),
            preserve_default=False,
        ),
    ]
