# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_item_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('NOT_SOLD', 'Not Sold'), ('SOLD', 'Sold')], default='NOT_SOLD', max_length=100),
        ),
    ]
