# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_auto_20170213_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='visibility',
            field=models.CharField(choices=[('Visible', 'Visible'), ('Invisible', 'Invisible')], default=True, max_length=30),
            preserve_default=False,
        ),
    ]
