# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 22:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_auto_20170304_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrderDetails',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shopify.Item')),
                ('charge_id', models.IntegerField(null=True)),
                ('transfer_id', models.IntegerField(null=True)),
                ('order_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='order_data',
        ),
    ]
