# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0005_item_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='visibility',
        ),
        migrations.AddField(
            model_name='item',
            name='is_visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
