# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0005_auto_20170304_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorderdetails',
            name='charge_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
