# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0005_item_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='visibility',
            field=models.BooleanField(),
        ),
    ]
