# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0006_auto_20170324_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('webhook_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
