# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0008_auto_20170324_0526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webhook',
        ),
    ]
