# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
