# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shipment',
        ),
        migrations.AddField(
            model_name='shipment',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
