# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20170202_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
