# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_auto_20170206_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
