# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_auto_20170215_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_physical',
            field=models.BooleanField(default=False),
        ),
    ]
