# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipment_is_physical'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created']},
        ),
    ]
