# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_auto_20170216_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-modified']},
        ),
    ]
