# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ManyToManyField(to='knowledge.FAQCategory'),
        ),
    ]
